#' @title Indivdual License Portfolio
#' @description DATASET_DESCRIPTION
#' @format A data frame with 170055 rows and 115 variables:
#' \describe{
#'   \item{landings_number}{double COLUMN_DESCRIPTION}
#'   \item{license_year}{double COLUMN_DESCRIPTION}
#'   \item{LC3}{double COLUMN_DESCRIPTION}
#'   \item{LC1}{double COLUMN_DESCRIPTION}
#'   \item{LNC}{double COLUMN_DESCRIPTION}
#'   \item{LC2}{double COLUMN_DESCRIPTION}
#'   \item{LC3O}{double COLUMN_DESCRIPTION}
#'   \item{LCO}{double COLUMN_DESCRIPTION}
#'   \item{LCS}{double COLUMN_DESCRIPTION}
#'   \item{LC2O}{double COLUMN_DESCRIPTION}
#'   \item{LA}{double COLUMN_DESCRIPTION}
#'   \item{NLC1}{double COLUMN_DESCRIPTION}
#'   \item{LCU}{double COLUMN_DESCRIPTION}
#'   \item{LAU}{double COLUMN_DESCRIPTION}
#'   \item{PLC3}{double COLUMN_DESCRIPTION}
#'   \item{DL}{double COLUMN_DESCRIPTION}
#'   \item{PLC1}{double COLUMN_DESCRIPTION}
#'   \item{PLC2}{double COLUMN_DESCRIPTION}
#'   \item{MLC1}{double COLUMN_DESCRIPTION}
#'   \item{LAO}{double COLUMN_DESCRIPTION}
#'   \item{DS}{double COLUMN_DESCRIPTION}
#'   \item{NA}{double COLUMN_DESCRIPTION}
#'   \item{SWR}{double COLUMN_DESCRIPTION}
#'   \item{PELD}{double COLUMN_DESCRIPTION}
#'   \item{MWD}{double COLUMN_DESCRIPTION}
#'   \item{CS}{double COLUMN_DESCRIPTION}
#'   \item{SD}{double COLUMN_DESCRIPTION}
#'   \item{SUWT}{double COLUMN_DESCRIPTION}
#'   \item{E2}{double COLUMN_DESCRIPTION}
#'   \item{E1C}{double COLUMN_DESCRIPTION}
#'   \item{NCS}{double COLUMN_DESCRIPTION}
#'   \item{E1}{double COLUMN_DESCRIPTION}
#'   \item{PELF}{double COLUMN_DESCRIPTION}
#'   \item{PCS}{double COLUMN_DESCRIPTION}
#'   \item{SUB}{double COLUMN_DESCRIPTION}
#'   \item{SUH}{double COLUMN_DESCRIPTION}
#'   \item{E2C}{double COLUMN_DESCRIPTION}
#'   \item{TEN}{double COLUMN_DESCRIPTION}
#'   \item{QM}{double COLUMN_DESCRIPTION}
#'   \item{SWRO}{double COLUMN_DESCRIPTION}
#'   \item{PSUS}{double COLUMN_DESCRIPTION}
#'   \item{PSSH}{double COLUMN_DESCRIPTION}
#'   \item{PCFS}{double COLUMN_DESCRIPTION}
#'   \item{E0}{double COLUMN_DESCRIPTION}
#'   \item{SW}{double COLUMN_DESCRIPTION}
#'   \item{CSO}{double COLUMN_DESCRIPTION}
#'   \item{CSU}{double COLUMN_DESCRIPTION}
#'   \item{GC}{double COLUMN_DESCRIPTION}
#'   \item{SDI}{double COLUMN_DESCRIPTION}
#'   \item{NCP}{double COLUMN_DESCRIPTION}
#'   \item{NCF}{double COLUMN_DESCRIPTION}
#'   \item{E0C}{double COLUMN_DESCRIPTION}
#'   \item{PTEN}{double COLUMN_DESCRIPTION}
#'   \item{E6}{double COLUMN_DESCRIPTION}
#'   \item{MAED}{double COLUMN_DESCRIPTION}
#'   \item{MD}{double COLUMN_DESCRIPTION}
#'   \item{MAEF}{double COLUMN_DESCRIPTION}
#'   \item{NBED}{double COLUMN_DESCRIPTION}
#'   \item{MH}{double COLUMN_DESCRIPTION}
#'   \item{SWS}{double COLUMN_DESCRIPTION}
#'   \item{PSD}{double COLUMN_DESCRIPTION}
#'   \item{PSUB}{double COLUMN_DESCRIPTION}
#'   \item{SDT}{double COLUMN_DESCRIPTION}
#'   \item{NBEF}{double COLUMN_DESCRIPTION}
#'   \item{EP}{double COLUMN_DESCRIPTION}
#'   \item{SCD}{double COLUMN_DESCRIPTION}
#'   \item{PSSU}{double COLUMN_DESCRIPTION}
#'   \item{NRSS}{double COLUMN_DESCRIPTION}
#'   \item{MIDF}{double COLUMN_DESCRIPTION}
#'   \item{PSDI}{double COLUMN_DESCRIPTION}
#'   \item{PSUH}{double COLUMN_DESCRIPTION}
#'   \item{E6C}{double COLUMN_DESCRIPTION}
#'   \item{NRS}{double COLUMN_DESCRIPTION}
#'   \item{SURF}{double COLUMN_DESCRIPTION}
#'   \item{NBEF2}{double COLUMN_DESCRIPTION}
#'   \item{PCPS}{double COLUMN_DESCRIPTION}
#'   \item{MISD}{double COLUMN_DESCRIPTION}
#'   \item{SUR}{double COLUMN_DESCRIPTION}
#'   \item{PSCF}{double COLUMN_DESCRIPTION}
#'   \item{NBAL}{double COLUMN_DESCRIPTION}
#'   \item{MISDT}{double COLUMN_DESCRIPTION}
#'   \item{MIDFC}{double COLUMN_DESCRIPTION}
#'   \item{CPS}{double COLUMN_DESCRIPTION}
#'   \item{CFS}{double COLUMN_DESCRIPTION}
#'   \item{CFC}{double COLUMN_DESCRIPTION}
#'   \item{CPC}{double COLUMN_DESCRIPTION}
#'   \item{MENR}{double COLUMN_DESCRIPTION}
#'   \item{MENC}{double COLUMN_DESCRIPTION}
#'   \item{PSUL}{double COLUMN_DESCRIPTION}
#'   \item{PCFC}{double COLUMN_DESCRIPTION}
#'   \item{NBSD}{double COLUMN_DESCRIPTION}
#'   \item{NBCS}{double COLUMN_DESCRIPTION}
#'   \item{NBCFS}{double COLUMN_DESCRIPTION}
#'   \item{NBMD}{double COLUMN_DESCRIPTION}
#'   \item{GCN}{double COLUMN_DESCRIPTION}
#'   \item{AL}{double COLUMN_DESCRIPTION}
#'   \item{MIEF}{double COLUMN_DESCRIPTION}
#'   \item{NBEDF}{double COLUMN_DESCRIPTION}
#'   \item{PELDC}{double COLUMN_DESCRIPTION}
#'   \item{PELFC}{double COLUMN_DESCRIPTION}
#'   \item{MICS}{double COLUMN_DESCRIPTION}
#'   \item{MIMWD}{double COLUMN_DESCRIPTION}
#'   \item{PSW}{double COLUMN_DESCRIPTION}
#'   \item{NBSC}{double COLUMN_DESCRIPTION}
#'   \item{NBSL}{double COLUMN_DESCRIPTION}
#'   \item{NBSS}{double COLUMN_DESCRIPTION}
#'   \item{NTP}{double COLUMN_DESCRIPTION}
#'   \item{VH}{double COLUMN_DESCRIPTION}
#'   \item{SPT}{double COLUMN_DESCRIPTION}
#'   \item{NBMH}{double COLUMN_DESCRIPTION}
#'   \item{PAL}{double COLUMN_DESCRIPTION}
#'   \item{CAR}{double COLUMN_DESCRIPTION}
#'   \item{NBSF}{double COLUMN_DESCRIPTION}
#'   \item{NBEF2C}{double COLUMN_DESCRIPTION}
#'   \item{MENNR}{double COLUMN_DESCRIPTION}
#'}
#' @details DETAILS
"ind_lic_portfolio"
